
[font]
normal = { family = "0xProtoNerdFontMono", style = "Regular" }
size = 10

[keyboard]
bindings = [
  { key = "V", mods = "Control", action = "Paste" },
  { key = "C", mods = "Control", action = "Copy" },
  { key = "C", mods = "Control|Shift", chars = "\u0003"}
]

[general]
import = [
"/home/highpingblorg/.config/alacritty/enfocado_dark.toml",
]
